#The `backend` Deployment will be configured to prevent modifications to the local filesystem and ensure that `/tmp` is writable. We can achieve this by using an `emptyDir` volume for `/tmp` and setting the security context to make the filesystem read-only.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: your-backend-image
        volumeMounts:
        - name: tmp-volume
          mountPath: /tmp
      volumes:
      - name: tmp-volume
        emptyDir: {}
      securityContext:
        readOnlyRootFilesystem: true
      readinessProbe:
        tcpSocket:
          port: 6379
        initialDelaySeconds: 10
        periodSeconds: 5
      livenessProbe:
        exec:
          command:
          - "true"
        initialDelaySeconds: 10
        periodSeconds: 5
